# Optimum Polynomial
https://projecteuler.net/problem=101

If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function, 
$u_n = n^3: 1, 8, 27, 64, 125, 216, ...$

Suppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define $OP(k, n)$ to be the nth term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that $OP(k, n)$ will accurately generate the terms of the sequence for n ≤ k, and potentially the first incorrect term (FIT) will be $OP(k, k+1)$; in which case we shall call it a bad OP (BOP).

![image](101_img.png)

# Problem Statement
(In my own words)

Given a polynomial, the curve that interpolates the first $n=1,2,...,10$ points with polynomials of degree $n-1$ is called an Optimum Polynomial (OP). An OP that doesn't match all points of the polynomial is called a Bad Optmimum Polynomial (BOP). The value of the BOP at the first value that doesn't match the polynomial is called the First Incorrect Term (FIT). 

Find the sum of the FITs for the tenth degree polynomial function:
$f(x) = 1 - x + x^2 - x^3 + x^4 - x^5 + x^6 - x^7 + x^8 - x^9 + x^{10}$

# Planning
* Create function for 0th degree polynomial
* Import function for interpolating 

For each n:
* generate the first [large number] elements of f(x)$
* find the FIT value, using common sense or the polynomial function

# Implementation


In [4]:
import numpy as np

In [54]:
def polynomialFunction(coeffs, xList):
    """
    intakes a list of n coefficients for a polynomial of n-1 degree
    coefficients are listed in decreasing order of power
    
    n may be less than len(xList) - repurposed for curve fitting
    
    returns yList
    """
    
        
    
    def poly(coeffs, x):
        length = len(coeffs)
        output = 0
        for i in range(length):
            output += coeffs[i]*np.power(x, length-1-i)
        return output
    
    return poly(coeffs, xList)

In [55]:
np.power([1,2,3,4,5,6,7,8,9], 11) - np.power([1,2,3,4,5,6,7,8,9], 10)

array([          0,        1024,      118098,     3145728,    39062500,
         302330880,  1694851494, -1073741824,  2124471432], dtype=int32)

In [52]:
def getPolyCoeffs(x,y):
    """
    intakes two lists of same length
    """
    length = len(x)
    A = np.zeros((length,length))
    b = np.zeros((length,1))
    
    for i in range(length):
        b[i] = y[i]
        for j in range(length):
            A[i][j] = np.power(x[i], length-1 - j)
            
    return np.linalg.inv(A).dot(b)

In [11]:
#test
testCoeffs = getPolyCoeffs([1],[1]) # 0th order polynomial
print(polynomialFunction(testCoeffs, [1,2,3,4]))

[1. 1. 1. 1.]


# Results

In [16]:
def closeEnough(a, b, error):
    """makes double equality comparisons more forgiving"""
    return abs(a-b) <= error

In [78]:
tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 12))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
print(f_x)
print()

sumFIT = 0
errorBound = 0.5# for closeEnough() double equality comparison

for i in range(1, 11): # stops at order 10
    coeffs = getPolyCoeffs(x[:i], f_x[:i]) # this is likely where floating point rounding error is introduced
    f_x_OP = polynomialFunction(coeffs, x)
    
    
    for j in range(len(x)):
        if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
            sumFIT += round(f_x_OP[j],1) # rounds it to the nearest whole number, since it's approximated
            print(f"For n={i}, the OP({j+1})={f_x_OP[j]} is the FIT") # starts from index 1
            break
        if j == len(x)-1:
            print(f"Seems like {len(x)} terms wasn't enough")
            
    print([round(a,2) for a in f_x_OP])
    print()

print(sumFIT)
            
    

[          1         683       44287      838861     8138021    51828151
   247165843   954437177 -1156861335   500974499 -1993831225]

For n=1, the OP(2)=1.0 is the FIT
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

For n=2, the OP(3)=1365.0 is the FIT
[1.0, 683.0, 1365.0, 2047.0, 2729.0, 3411.0, 4093.0, 4775.0, 5457.0, 6139.0, 6821.0]

For n=3, the OP(4)=130813.0 is the FIT
[1.0, 683.0, 44287.0, 130813.0, 260261.0, 432631.0, 647923.0, 906137.0, 1207273.0, 1551331.0, 1938311.0]

For n=4, the OP(5)=3092453.000000001 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 3092453.0, 7513111.0, 14808883.0, 25687817.0, 40857961.0, 61027363.0, 86904071.0]

For n=5, the OP(6)=32740951.0000001 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 8138021.0, 32740951.0, 90492403.0, 202282697.0, 394047721.0, 696768931.0, 1146473351.0]

For n=6, the OP(7)=205015602.9999978 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 8138021.0, 51828151.0, 205015603.0, 603113897.0, 1462930921.0, 3101756131.0, 5956447751.0]

Fo

In [97]:
# the issue seems to be the precisino of th last FIT

Help with using decimal module for more precision:
* https://stackoverflow.com/questions/7770870/numpy-array-with-dtype-decimal
* https://docs.python.org/3/tutorial/floatingpoint.html 
* https://web.archive.org/web/20150110065945/http://en.literateprograms.org/Arbitrary-precision_elementary_mathematical_functions_%28Python%29

In [82]:
import decimal


num = 0
print(num + 1/3)

preciseNum = decimal.Decimal(0)
print(preciseNum + decimal.Decimal(1/3))

0.3333333333333333
0.3333333333333333148296162562


In [83]:
pow(preciseNum, 1)

Decimal('0')

In [96]:
# special investigation for n = 10
import decimal

tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 21))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
f_x = [int(val) for val in f_x] # convert to normal list

def getPrecisePolyCoeffs(x,y):
    """
    intakes two lists of same length
    """
    length = len(x)
    A = np.zeros((length,length))
    for row in A:
        for elem in row:
            elem = decimal.Decimal(elem)
    
    b = np.zeros((length,1))
    
    for i in range(length):
        b[i] = decimal.Decimal(y[i])
        for j in range(length):
            A[i][j] = pow(decimal.Decimal(x[i]), length-1 - j)
            
    return np.linalg.inv(A).dot(b)

coeffs = getPrecisePolyCoeffs(x[:10], f_x[:10])
print(coeffs)

f_x_OP = polynomialFunction(coeffs, x)


print("f(x):")
print(f_x)
print()

print("OP(x):")
print([float(a) for a in f_x_OP])
print()




# print(f_x)
# print(f_x_OP)
# # print([round(a,0) for a in f_x_OP])
# elem11 = polynomialFunction(coeffs, 11)

# elem11 = float(elem11)

# print(elem11)

# print(round(elem11, 0))

# if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
#     sumFIT += round(f_x_OP[j],0) # rounds it to the nearest whole number, since it's approximated
#     print(f"For n={i}, the OP({j})={f_x_OP[j]} is the FIT")
#     break
#     if j == len(x)-1:
#         print(f"Seems like {len(x)} terms wasn't enough")

[[ 8.29044494e+04]
 [-3.83611123e+06]
 [ 7.59328322e+07]
 [-8.41255534e+08]
 [ 5.72628236e+09]
 [-2.47084267e+10]
 [ 6.71328494e+10]
 [-1.09754281e+11]
 [ 9.67360191e+10]
 [-3.43633672e+10]]
f(x):
[1, 683, 44287, 838861, 8138021, 51828151, 247165843, 954437177, -1156861335, 500974499, -1993831225, 1319915205, -837562163, -611928337, -556138085, -252645135, 1323727185, -1886330341, 537291535, -1489776835]

OP(x):
[1.0, 682.9996795654297, 44286.99897766113, 838860.9958648682, 8138020.994949341, 51828150.99153137, 247165842.98579407, 954437176.9398956, -1156861335.092331, 500974498.9478302, -355940752259387.56, -355069891407168.5, -707527784790865.6, -1764121872346770.0, 1.3319154043362186e+16, 1.0902681891506386e+16, 2.3272471061222564e+16, 3.3678385371320784e+16, 4.0477972386461944e+16, 5.894539602942346e+16]

