# Optimum Polynomial
https://projecteuler.net/problem=101

If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function, 
$u_n = n^3: 1, 8, 27, 64, 125, 216, ...$

Suppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define $OP(k, n)$ to be the nth term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that $OP(k, n)$ will accurately generate the terms of the sequence for n ≤ k, and potentially the first incorrect term (FIT) will be $OP(k, k+1)$; in which case we shall call it a bad OP (BOP).

![image](101_img.png)

# Problem Statement
(In my own words)

Given a polynomial, the curve that interpolates the first $n=1,2,...,10$ points with polynomials of degree $n-1$ is called an Optimum Polynomial (OP). An OP that doesn't match all points of the polynomial is called a Bad Optmimum Polynomial (BOP). The value of the BOP at the first value that doesn't match the polynomial is called the First Incorrect Term (FIT). 

Find the sum of the FITs for the tenth degree polynomial function:
$f(x) = 1 - x + x^2 - x^3 + x^4 - x^5 + x^6 - x^7 + x^8 - x^9 + x^{10}$

# Planning
* Create function for 0th degree polynomial
* Import function for interpolating 

For each n:
* generate the first [large number] elements of f(x)$
* find the FIT value, using common sense or the polynomial function 
* 

## 11/9/19 update:
* 
* Disorganized thoughts:
    * 
    * I already did something without first planning it out in a [Planning block]...
        * whatever 
        * If I don't want this to happen again, I'd better define it clearly 
        * 
    *  
    * Is it okay to use functions that I've coded in the past?
        * 
        * The alterantive is coding them from scratch
            * perhaps a "waste of time," but shouldn't I be able to to dhis anyway?
            *  
        * 
        * I shouldn't be basing my solution on the avialability of tools...
            * 
            * Or, I could, but that would limit me severely in the future if I kept up the habit 
            *
        * 
    * 
    * (note: I already began planning in other areas, although not inside this file...)
        * 
        * should I try to make each of these problems completely self-contained?
            * is that even possible?
            * is that even desirable?
                * 
                * the overall aim is that I'll know where to find something in the future
                    * if I have a better system for consolidating my thoughts than just offline files, I should use it (?)
                    * 
                    * this shouldn't take priority over the main purpose of practicing my computatinoal skills, though
                        * 
                        * organization is something that can influence just aboutanything in my life retroactively and recursively (?)
                        * 
                    * 
                *
            *
        *
    * 
    * Does typing out my thoughts give me a sense of comfort?
        * 
        * Is this in any way practicable?
            * 
            * Actually, yes - it's good to know that in a file I have an immediate place to store thoughts, and that I've warmed up enough to be able to store them. If something arises spontaneously and I'm not ready to write it down before it dissipates, I'll regret my lack of preparation.
                * 
                *  
                *
            * 
            * 
            *
        * 
        * 
        
    * 
    * Possible course of action:
        * 
        * revisit code from previous, examine what it does
            * (note: I already did this =before writing this=)
        * 
        * edit old code slightly, apply it
            * instead of using numpy's matrix inversion to solve a system of equation, use matrix elimination
                * 
                * matrix inversion invokes double precision errors, when this could be solved for integral coefficients
                    * 
                    * do I know the coefficients will be integral? 
                    *
                * 
                * can I write a matrix elimination solver that maintains integral-ness whenever possible?
                    * 
                    * whis this would mean multipying [pivot entries] instead of dividing, whenever possible
                        * 
                        * (I could write some more of my thoughts down here, but I don't need to)
                        * 
                        * do I already have such a function written somewhere?
                            * 
                            * should I be remembering this sort of thing, or should I be starting afresh?
                                * 
                                * in the interest of time, rememberng might be a better option
                                * 
                            *
                        *
                    * 
                * 
            * 
            * 
            * 
        * 
        * 
        * 
    * 
    * NOte: this notebook follows an old organization convention - for now I don't think I'll be able to care about organizing stuff in the proper way (without distracting from the central stuff) 
    *
* 
* 

### [Problem Planning]
* (=note:= made a separate notebook block, since the above planning blocks are filled with other, non-relevant stuff)
* 
* (what if I did this without writing my planning down?)
    * ( do I still need to prove that I can? )
        * (is this important _right now_ ?)
    * 
* 
* OUtline:
    * 
    * Reuse old solution, swap out one part
        *  
        * 
        * 
    * 
    * 
* 
*  
* 
*
* 

# Implementation


## Tinkering

In [40]:
## how to create an augmented matrix?
import numpy as np

mat_1 = np.array([[1,0], [0,1]])
vec = np.array([[1], [2]])

print(mat_1, vec)

# aug_mat = mat_1.append(vec)
# aug_mat = np.concatenate(mat_1, vec)
aug_mat = np.concatenate((mat_1, vec), axis=1)

print(aug_mat)

[[1 0]
 [0 1]] [[1]
 [2]]
[[1 0 1]
 [0 1 2]]


In [42]:
## testing - suppressing prints from function
def print_function():
    print('something printed')
    
print_function()
print_function();
print('something printed');

something printed
something printed
something printed


In [57]:
## retreiving a column vector from a matrix
matrix_A = np.zeros((3,3))
# vector_a = matrix_A[:][-1]
vector_a = matrix_A[:][-1].reshape((3, 1))
vector_b = np.zeros((3, 1))

print(matrix_A)
print(vector_a)
print(vector_b)

# edit: this may have been misleading...

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]]


In [64]:
## get the vector from a 2 by 1 augmented matrix
small_aug_mat = np.array([[1, 1]])
small_vec = small_aug_mat[:][-1]

print(small_aug_mat)
print(small_vec)

[[1 1]]
[1 1]


In [66]:
## get the vector from an aug mat
aug_mat = np.array([[1,1], [2,2]])
# vec = aug_mat[:][1]
vec = aug_mat[:, 1] # aha!

print(aug_mat)
print(vec)

[[1 1]
 [2 2]]
[1 2]


In [75]:
## is there a caonincal power functions?
pow(2,2)

4

## Work

### Methods for polynomial solving stuff

In [1]:
import numpy as np

In [81]:
def polynomialFunction(coeffs, xList):
    """
    intakes a list of n coefficients for a polynomial of n-1 degree
    coefficients are listed in decreasing order of power
    
    n may be less than len(xList) - repurposed for curve fitting
    
    returns yList
    """
    
        
    
    def poly(coeffs, x):
        length = len(coeffs)
        output = 0
        for i in range(length):
#             output += coeffs[i]*np.power(x, length-1-i)

            # edit: using np.power invokes float precision errors
#             output += coeffs[i]*pow(x, length-1-i)
            output += coeffs[i] * x**(length-1-i)
            
        return output
    
#     return poly(coeffs, xList)
        # edit: my new function doesn't use numpy's paralel-structure
    return [poly(coeffs, x) for x in xList]

In [74]:
## testing
polynomialFunction([1,2,3], [4, 5, 6])
    # yuck - why do I need to use an np.power function?
        # is this the source of my floating point errors? 

array([27, 38, 51], dtype=int32)

In [82]:
## testing - after swapping power function
polynomialFunction([1,2,3], [4, 5, 6])


[27, 38, 51]

In [3]:
np.power([1,2,3,4,5,6,7,8,9], 11) - np.power([1,2,3,4,5,6,7,8,9], 10)

array([          0,        1024,      118098,     3145728,    39062500,
         302330880,  1694851494, -1073741824,  2124471432], dtype=int32)

In [67]:
def getPolyCoeffs(x,y):
    """
    intakes two lists of same length
    """
    length = len(x)
    A = np.zeros((length,length))
    b = np.zeros((length,1))
    
    for i in range(length):
#         b[i] = y[i]
        b[i][0] = y[i]
        for j in range(length):
#             A[i][j] = np.power(x[i], length-1 - j)
            ## 11/9/19 edit
            A[i][j] = int(np.power(x[i], length-1 - j))
            
    ## solve the system of equations
    
#     # using inverse
#     return np.linalg.inv(A).dot(b)

    # using [other method]
    aug_matrix = np.concatenate((A, b), axis = 1)
    
    gaussJordanElimWithoutPrinting(aug_matrix)
        
#     return aug_matrix[:][-1].reshape((length, 1))
    return aug_matrix[:,-1].reshape(length, 1)
    

In [5]:
#test
testCoeffs = getPolyCoeffs([1],[1]) # 0th order polynomial
print(polynomialFunction(testCoeffs, [1,2,3,4]))

[1. 1. 1. 1.]


In [68]:
## test after swapping out inverse solving for elimination solving
testCoeffs = getPolyCoeffs([1],[1]) # 0th order polynomial
print(polynomialFunction(testCoeffs, [1,2,3,4]))

[1. 1. 1. 1.]


### Methods for matrix eliination:

In [6]:
def isZeroRow(augMat, rowNum): # rowNum is ordinal
    n = len(augMat)
    rowOfZeroes = True
    
    for j in range(n):
        if augMat[rowNum - 1][j] != 0:
            rowOfZeroes = False
    
    return rowOfZeroes
        

In [7]:
## testing (?)

In [8]:
def isUnsolvableRow(augMat, rowNum):
    if(isZeroRow(augMat, rowNum)):
        if(augMat[rowNum - 1][len(augMat[0]) - 1] != 0):
            return True
    return False

In [9]:
def hasInfiniteSolutionsRow(augMat, rowNum):
    if(isZeroRow(augMat, rowNum)):
        if(augMat[rowNum - 1][len(augMat[0]) - 1] == 0):
            return True
    return False

In [10]:
def elimRow(mat, pivotRowNum): # the error prevention must occur outsiide this function
    # pivotRowNum - 1 is the practical pivot Row index
    """Given a matrix and a pivot row number, eliminates all numbers in pivot position of matrix beneath the pivot row"""
    for i in range(pivotRowNum, len(mat)):  # pivotRowNum is ordered ordinally, whereas indices are cardinal, but this starts at the row after the pivotRow
        mat[i] = mat[i] - np.multiply(mat[pivotRowNum - 1], mat[i][pivotRowNum - 1]/mat[pivotRowNum - 1][pivotRowNum - 1]) 
        
    

In [36]:
## edited elimRow for integral pivots/entries
    # this shouldn't make a difference for doubles?
def elimRow(mat, pivotRowNum):
    for i in range(pivotRowNum, len(mat)):
        # get least common multiple of pivot element and leading elements in each row
        lcm_var = int( lcm(mat[pivotRowNum-1][pivotRowNum-1], mat[i][pivotRowNum-1]) )
        
        # multiply row to get lcm
        mat[i] = np.multiply(mat[i], int( lcm_var/mat[i][pivotRowNum-1] ))
        
        # subtract pivot row multiplied by lcm/pivot element (should be integral)
        mat[i] = mat[i] - np.multiply( mat[pivotRowNum-1], int( lcm_var/mat[pivotRowNum-1][pivotRowNum-1] ) )

In [35]:
def lcm(a, b):
    # returns least common multiple of a and b, if integral
#     if isinstance(a, int) and isinstance(b, int):
#         return a*b/gcd(a,b)
#     else:
#         print('Error in lcm(a,b): non-integer inputs')
    if not (isinstance(a, int) and isinstance(b, int)): # i can foresee an error here
        print('Error in gcd(a,b): non-integer inputs')
    return a*b/gcd(a,b)

In [23]:
## testing
lcm(17, 100)



1700.0

In [24]:
## side tinkering
print(17/1) # division, even if it's of integers, automatically updrades to double type???

17.0


In [18]:
def gcd(a, b):
    if not (isinstance(a, int) and isinstance(b, int)): # i can foresee an error here
        print('Error in gcd(a,b): non-integer inputs')
    
    # ensure a is bigger than b
    if a < b:
        temp = a
        a = b
        b = temp
        
    r = a%b
    
    while r!=0:
        a = b
        b = r
        r = a%b
        
    return b

In [19]:
## testing
gcd(100, 25)

25

In [20]:
## more testing
gcd(17, 100)

1

In [21]:
## testing
gcd(17.0, 100.0)

Error in gcd(a,b): non-integer inputs


1.0

In [11]:
def swapCheck(augMat, pivotRowNum): #accepts pivot row num as ordinal
    # if n - pivotRowNum rows are tried without success, then there exists no next pivot row
        # then just move on to the next row
    """Given a matrix and a pivot row number, checks if pivot row has a 0 pivot, and tries to swap if so"""
    for i in range(pivotRowNum, len(augMat)): # will try (n - pivotRowNum) swaps
        if augMat[pivotRowNum - 1][pivotRowNum - 1] == 0: # iterate through rows with indices pivotRowNum - n-1
            tempRow = augMat[pivotRowNum]
            augMat[pivotRowNum] = augMat[i]
            augMat[i] = augMat[pivotRowNum]
        else:
            break # breaks out of for loop
    
# concern: if a row of all 0s, nothing will stop

In [12]:
def gaussElim(augMat):
    solutionType = "Unique"
    n = len(augMat) # assumes it will be given an n by n+1 augmented matrix
    for i in range(n):
        if isUnsolvableRow(augMat, i + 1):
            solutionType = "None"
            break
        elif hasInfiniteSolutionsRow(augMat, i + 1):
            solutionType = "Infinite"
            break
        swapCheck(augMat, i + 1) #ordinal to cardinal
        elimRow(augMat, i + 1)
    print(f"Solution type: {solutionType}")
    print("Final matrix:")
    print(np.array(augMat))

In [13]:
def backElimRow(mat, pivotRowNum): # the error prevention must occur outsiide this function
    # pivotRowNum - 1 is the practical pivot Row index
    """Given a matrix and a pivot row number, eliminates all numbers in pivot position of matrix above the pivot row"""
    mat[pivotRowNum - 1] = np.multiply(mat[pivotRowNum - 1], 1/mat[pivotRowNum - 1][pivotRowNum - 1])
 
    for i in range(pivotRowNum - 1):

        mat[i] = mat[i] - np.multiply(mat[pivotRowNum - 1], mat[i][pivotRowNum - 1]/mat[pivotRowNum - 1][pivotRowNum - 1])
    
    
    

In [14]:
def gaussJordanElim(augMat):
    """A function that performs Gaussian elimination and then Gauss Jordan elimination on a matrix,
    only if it is full rank and has one unique solution"""
    solutionType = "Unique"
    n = len(augMat) # assumes it will be given an n by n+1 augmented matrix
    for i in range(n):
        if isUnsolvableRow(augMat, i + 1):
            solutionType = "None"
            break
        elif hasInfiniteSolutionsRow(augMat, i + 1):
            solutionType = "Infinite"
            break
        swapCheck(augMat, i + 1) #ordinal to cardinal
        elimRow(augMat, i + 1)
        
    print("Stage 1 - Gauss Elim:")
    print(f"Solution type: {solutionType}")
    print("Final Matrix")
    print(np.array(augMat))
    print()
    
    if solutionType == "Unique":
        for i in range(n):
            backElimRow(augMat, len(augMat) - i)
    
        print("Stage 2 - Gauss Jordan Elim:")
        print("Final matrix:")
        print(np.array(augMat))
    

In [43]:
## edited version without printing
# def gauss_jordan_elim(augMat):
def gaussJordanElimWithoutPrinting(augMat):
    """A function that performs Gaussian elimination and then Gauss Jordan elimination on a matrix,
    only if it is full rank and has one unique solution"""
    solutionType = "Unique"
    n = len(augMat) # assumes it will be given an n by n+1 augmented matrix
    for i in range(n):
        if isUnsolvableRow(augMat, i + 1):
            solutionType = "None"
            break
        elif hasInfiniteSolutionsRow(augMat, i + 1):
            solutionType = "Infinite"
            break
        swapCheck(augMat, i + 1) #ordinal to cardinal
        elimRow(augMat, i + 1)
        
#     print("Stage 1 - Gauss Elim:")
#     print(f"Solution type: {solutionType}")
#     print("Final Matrix")
#     print(np.array(augMat))
#     print()
    
    if solutionType == "Unique":
        for i in range(n):
            backElimRow(augMat, len(augMat) - i)
    
#         print("Stage 2 - Gauss Jordan Elim:")
#         print("Final matrix:")
#         print(np.array(augMat))
    

In [ ]:
## testing: gauss jordan without printing
    # actually, no need

In [17]:
## testing - before editing elimRow()
aug_matrix = [
    [1, 3, 4, 5, 10, 9],
    [2, 2, 2, 5, 10, 15],
    [17,19,23, 1, 2, 3]
]

print(gaussJordanElim(aug_matrix))

Stage 1 - Gauss Elim:
Solution type: Unique
Final Matrix
[[   1.    3.    4.    5.   10.    9.]
 [   0.   -4.   -6.   -5.  -10.   -3.]
 [   0.    0.    3.  -44.  -88. -126.]]

Stage 2 - Gauss Jordan Elim:
Final matrix:
[[  1.           0.           0.          -6.08333333 -12.16666667
  -14.25      ]
 [ -0.           1.          -0.          23.25        46.5
   63.75      ]
 [  0.           0.           1.         -14.66666667 -29.33333333
  -42.        ]]
None


In [37]:
## testing - after editing elimRow()
aug_matrix = [
    [1, 3, 4, 5, 10, 9],
    [2, 2, 2, 5, 10, 15],
    [17,19,23, 1, 2, 3]
]

print(gaussJordanElim(aug_matrix))

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Stage 1 - Gauss Elim:
Solution type: Unique
Final Matrix
[[   1    3    4    5   10    9]
 [   0   -4   -6   -5  -10   -3]
 [   0    0    3  -44  -88 -126]]

Stage 2 - Gauss Jordan Elim:
Final matrix:
[[  1.           0.           0.          -6.08333333 -12.16666667
  -14.25      ]
 [ -0.           1.          -0.          23.25        46.5
   63.75      ]
 [  0.           0.           1.         -14.66666667 -29.33333333
  -42.        ]]
None


# Results

In [71]:
def closeEnough(a, b, error):
    """makes double equality comparisons more forgiving"""
    return abs(a-b) <= error

In [78]:
tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 12))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
print(f_x)
print()

sumFIT = 0
errorBound = 0.5# for closeEnough() double equality comparison

for i in range(1, 11): # stops at order 10
    coeffs = getPolyCoeffs(x[:i], f_x[:i]) # this is likely where floating point rounding error is introduced
    f_x_OP = polynomialFunction(coeffs, x)
    
    
    for j in range(len(x)):
        if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
            sumFIT += round(f_x_OP[j],1) # rounds it to the nearest whole number, since it's approximated
            print(f"For n={i}, the OP({j+1})={f_x_OP[j]} is the FIT") # starts from index 1
            break
        if j == len(x)-1:
            print(f"Seems like {len(x)} terms wasn't enough")
            
    print([round(a,2) for a in f_x_OP])
    print()

print(sumFIT)
            
    

[          1         683       44287      838861     8138021    51828151
   247165843   954437177 -1156861335   500974499 -1993831225]

For n=1, the OP(2)=1.0 is the FIT
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

For n=2, the OP(3)=1365.0 is the FIT
[1.0, 683.0, 1365.0, 2047.0, 2729.0, 3411.0, 4093.0, 4775.0, 5457.0, 6139.0, 6821.0]

For n=3, the OP(4)=130813.0 is the FIT
[1.0, 683.0, 44287.0, 130813.0, 260261.0, 432631.0, 647923.0, 906137.0, 1207273.0, 1551331.0, 1938311.0]

For n=4, the OP(5)=3092453.000000001 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 3092453.0, 7513111.0, 14808883.0, 25687817.0, 40857961.0, 61027363.0, 86904071.0]

For n=5, the OP(6)=32740951.0000001 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 8138021.0, 32740951.0, 90492403.0, 202282697.0, 394047721.0, 696768931.0, 1146473351.0]

For n=6, the OP(7)=205015602.9999978 is the FIT
[1.0, 683.0, 44287.0, 838861.0, 8138021.0, 51828151.0, 205015603.0, 603113897.0, 1462930921.0, 3101756131.0, 5956447751.0]

Fo

In [97]:
# the issue seems to be the precisino of th last FIT

Help with using decimal module for more precision:
* https://stackoverflow.com/questions/7770870/numpy-array-with-dtype-decimal
* https://docs.python.org/3/tutorial/floatingpoint.html 
* https://web.archive.org/web/20150110065945/http://en.literateprograms.org/Arbitrary-precision_elementary_mathematical_functions_%28Python%29

In [82]:
import decimal


num = 0
print(num + 1/3)

preciseNum = decimal.Decimal(0)
print(preciseNum + decimal.Decimal(1/3))

0.3333333333333333
0.3333333333333333148296162562


In [83]:
pow(preciseNum, 1)

Decimal('0')

In [96]:
# special investigation for n = 10
import decimal

tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 21))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
f_x = [int(val) for val in f_x] # convert to normal list

def getPrecisePolyCoeffs(x,y):
    """
    intakes two lists of same length
    """
    length = len(x)
    A = np.zeros((length,length))
    for row in A:
        for elem in row:
            elem = decimal.Decimal(elem)
    
    b = np.zeros((length,1))
    
    for i in range(length):
        b[i] = decimal.Decimal(y[i])
        for j in range(length):
            A[i][j] = pow(decimal.Decimal(x[i]), length-1 - j)
            
    return np.linalg.inv(A).dot(b)

coeffs = getPrecisePolyCoeffs(x[:10], f_x[:10])
print(coeffs)

f_x_OP = polynomialFunction(coeffs, x)


print("f(x):")
print(f_x)
print()

print("OP(x):")
print([float(a) for a in f_x_OP])
print()




# print(f_x)
# print(f_x_OP)
# # print([round(a,0) for a in f_x_OP])
# elem11 = polynomialFunction(coeffs, 11)

# elem11 = float(elem11)

# print(elem11)

# print(round(elem11, 0))

# if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
#     sumFIT += round(f_x_OP[j],0) # rounds it to the nearest whole number, since it's approximated
#     print(f"For n={i}, the OP({j})={f_x_OP[j]} is the FIT")
#     break
#     if j == len(x)-1:
#         print(f"Seems like {len(x)} terms wasn't enough")

[[ 8.29044494e+04]
 [-3.83611123e+06]
 [ 7.59328322e+07]
 [-8.41255534e+08]
 [ 5.72628236e+09]
 [-2.47084267e+10]
 [ 6.71328494e+10]
 [-1.09754281e+11]
 [ 9.67360191e+10]
 [-3.43633672e+10]]
f(x):
[1, 683, 44287, 838861, 8138021, 51828151, 247165843, 954437177, -1156861335, 500974499, -1993831225, 1319915205, -837562163, -611928337, -556138085, -252645135, 1323727185, -1886330341, 537291535, -1489776835]

OP(x):
[1.0, 682.9996795654297, 44286.99897766113, 838860.9958648682, 8138020.994949341, 51828150.99153137, 247165842.98579407, 954437176.9398956, -1156861335.092331, 500974498.9478302, -355940752259387.56, -355069891407168.5, -707527784790865.6, -1764121872346770.0, 1.3319154043362186e+16, 1.0902681891506386e+16, 2.3272471061222564e+16, 3.3678385371320784e+16, 4.0477972386461944e+16, 5.894539602942346e+16]



### 11/9/19 try

In [73]:
tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 12))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
print(f_x)
print()

sumFIT = 0
errorBound = 0.5# for closeEnough() double equality comparison

for i in range(1, 11): # stops at order 10
    coeffs = getPolyCoeffs(x[:i], f_x[:i]) # this is likely where floating point rounding error is introduced
    f_x_OP = polynomialFunction(coeffs, x)
    
    
    for j in range(len(x)):
#         if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
            
        # edit: I'm not settling for double precision errors here
        if f_x[j] != f_x_OP[j]:

            sumFIT += round(f_x_OP[j],1) # rounds it to the nearest whole number, since it's approximated
            print(f"For n={i}, the OP({j+1})={f_x_OP[j]} is the FIT") # starts from index 1
            break
        if j == len(x)-1:
            print(f"Seems like {len(x)} terms wasn't enough")
            
    print([round(a,2) for a in f_x_OP])
    print()

print(sumFIT)
            
    

[          1         683       44287      838861     8138021    51828151
   247165843   954437177 -1156861335   500974499 -1993831225]

For n=1, the OP(2)=1 is the FIT
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
For n=2, the OP(3)=1365 is the FIT
[1, 683, 1365, 2047, 2729, 3411, 4093, 4775, 5457, 6139, 6821]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
For n=3, the OP(4)=130813 is the FIT
[1, 683, 44287, 130813, 260261, 432631, 647923, 906137, 1207273, 1551331, 1938311]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error i

### Some things that went wrong:
* I should be using Python's integers, not numpy's decimal-whatevers
    * I located the error in polynomialFunc()
* 
* This is turning into spaghetti-code, as I frantically make changes to things I don't fully understand
    * Perhaps I should try again later, with a fresh mind and perhaps a blank file
        * 
        * unless the immediate completion is necessary for my satisfaction? 
        *
* 

#### Another try

In [89]:
tenthDegreeCoeffs = [1,-1,1,-1,1,-1,1,-1,1,-1,1]
x = list(range(1, 12))
f_x = polynomialFunction(tenthDegreeCoeffs, x)
print(f_x)
print()

sumFIT = 0
errorBound = 0.5# for closeEnough() double equality comparison

for i in range(1, 11): # stops at order 10
    coeffs = getPolyCoeffs(x[:i], f_x[:i]) # this is likely where floating point rounding error is introduced
    
    ## edit: casting from float to integer
        # these should all be integers anyways?
    coeffs = [int(c) for c in coeffs]
    
    ## haphazard, frantic testing
#     print(coeffs)
    
    f_x_OP = polynomialFunction(coeffs, x)
    
    
    for j in range(len(x)):
#         if not closeEnough(f_x[j], f_x_OP[j], errorBound): # the first incorrect term
            
        # edit: I'm not settling for double precision errors here
        if f_x[j] != f_x_OP[j]:

#             sumFIT += round(f_x_OP[j],1) # rounds it to the nearest whole number, since it's approximated

            sumFIT += f_x_OP[j]

            print(f"For n={i}, the OP({j+1})={f_x_OP[j]} is the FIT") # starts from index 1
            break
        if j == len(x)-1:
            print(f"Seems like {len(x)} terms wasn't enough")
            
    print([round(a,2) for a in f_x_OP])
    print()

print(sumFIT)
            
    

[1, 683, 44287, 838861, 8138021, 51828151, 247165843, 954437177, 3138105961, 9090909091, 23775972551]

For n=1, the OP(2)=1 is the FIT
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
For n=2, the OP(3)=1365 is the FIT
[1, 683, 1365, 2047, 2729, 3411, 4093, 4775, 5457, 6139, 6821]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
For n=3, the OP(4)=130813 is the FIT
[1, 683, 44287, 130813, 260261, 432631, 647923, 906137, 1207273, 1551331, 1938311]

Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Error in gcd(a,b): non-integer inputs
Er

#### promise to myself: 
if the above solution doesn't work, I'll stop this goose chase for now and resume it another time

# Learning
* 
* Is there something about the philosophy of creating new files vs updating old files that I touched upon inadvertently here? 
* 
* Did I learn something about the relative importance of superficial things over tangible things? 
*
* When to edit vs when to rewrite code: 
    * 
    * https://stackoverflow.com/questions/1064403/when-to-rewrite-a-code-base-from-scratch
    * 
    * 
    
* Checking for type in python: https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python
* slicing np arrays: https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/
* 
* can integers overflow in python? https://mortada.net/can-integer-operations-overflow-in-python.html
* 
*  
## Reflection:
I might have to start this over from scratch...
* don't underestimate the frustration and stagnation caused by poorly, messily written code
* 
* 