# Path sum: two ways

(https://projecteuler.net/problem=81)

In the 5 by 5 matrix below, the minimal path sum from the top left to the bottom right, by only moving to the right and down, is indicated in bold red and is equal to 2427.

![An image](081_img.PNG)

Find the minimal path sum, in matrix.txt (right click and "Save Link/Target As..."), a 31K text file containing a 80 by 80 matrix, from the top left to the bottom right by only moving right and down.

In [4]:
# S: 12:46
# Unfinished: 2:15 

In [29]:
# doodling
testArray = np.array([[131, 673, 234, 103, 18], [201, 96, 342, 965, 150],[630, 803, 746, 422, 111], [537, 699, 497, 121, 956], [805, 732, 524, 37, 331]])


In [31]:
# finding row sums
rowSums = [sum(row) for row in testArray] 
print(rowSums)

[1159, 1754, 2712, 2810, 2429]


In [32]:
# finding column sums 
colSums = [sum(row) for row in np.transpose(testArray)]
print(colSums)

[2304, 3003, 2343, 1648, 1566]


In [6]:
print(testArray)

[[131 673 234 103  18]
 [201  96 342 965 150]
 [630 803 746 422 111]
 [537 699 497 121 956]
 [805 732 524  37 331]]


In [7]:
(testArray.dot(testArray))

array([[ 369655,  425846,  496007,  774815,  233708],
       [ 900042, 1203450,  893203,  379982, 1028170],
       [1029882, 1476346, 1246460, 1209766,  654769],
       [1358513, 1611967, 1296559,  989593,  601795],
       [ 869031, 1300964, 1021451, 1027147,  327387]])

In [8]:
start = timeit.default_timer()

for i in range(int(1e8)):
    True == True
    
end = timeit.default_timer()

print(end-start)

7.71477180627386


In [9]:
# string to int?

int('33')

strList = ['342', '3', '234', '11']

print([int(x) for x in strList])

[342, 3, 234, 11]


In [10]:
'Bob, mary, dingo, 33,11,11'.split(',')

['Bob', ' mary', ' dingo', ' 33', '11', '11']

In [4]:
import numpy as np
import timeit 


### Planning

* Figure out how to load .txt file as matrix

* Implement a solution for the 5x5 case that isn't brute force
    * Does this involve Djikstra's algorithm? 
    * I want to find the least-heavily weighted path
    * compare the two choices at each stage 
        * write a function that returns a list of index tuples representing a path taken
        * start from the top and the bottom and see where they meet - write a function to return matches 
            * write a function to calculate the sums for each of these matched paths
        * 

Note: I see an easy way to make any given matrix very hard to evalute using a general function, 
but I don't know if the creators of the problem are that cruel...


### Implementation

In [12]:
# get matrix from file

file = open('081_matrix.txt')

anArray = np.zeros((80, 80))

for i in range(80):
    aLine = file.readline()
    aLine = aLine.split(',') # the file has no spaces, thankfully
    tempRow = [int(x) for x in aLine] # convert string ints into ints
    anArray[i, :] = tempRow # set row of array
    
file.close()

print(anArray)

[[4445. 2697. 5115. ... 2758. 3748. 5870.]
 [1096.   20. 1318. ... 4187. 9353. 9377.]
 [9607. 7385.  521. ... 9515. 6385. 9230.]
 ...
 [2265. 8192. 1763. ... 7456. 5128. 5294.]
 [2132. 8992. 8160. ... 5634. 1113. 5789.]
 [5304. 5499.  564. ... 2751. 3406. 7981.]]


In [13]:
def pathLeastResistanceDown(matrix):
    """
    returns a list of coordinate tuples 
    at every coordinate pair, the one with the smallest value (between the right-adjacent and lower-adjacent choices) is chosen next
    the path ends when one of the sides of the matrix is reached
    starts at the top
    """
    x = 0
    y = 0
    path = [(x,y)] # instantiation
    
    while x < len(matrix)-1 and y < len(matrix[0])-1: # ends when a wall is reached
        if matrix[x+1, y] < matrix[x, y+1]:
            x+=1    
        elif matrix[x, y+1] < matrix[x+1, y]:
            y+=1      
        else:
            print("Wow, two adjacent choices are exactly the same. That's unexpected")
            break
        
        path.append( (x,y) ) 
        
    return path
    
    

In [14]:
# testing
pathLeastResistanceDown(testArray)

[(0, 0), (1, 0), (1, 1), (1, 2), (2, 2), (2, 3), (2, 4)]

In [15]:
def pathLeastResistanceDownComplete(matrix):
    """
    returns a list of coordinate tuples 
    at every coordinate pair, the one with the smallest value (between the right-adjacent and lower-adjacent choices) is chosen next
    the path ends when the bottom is reached
    starts at the top
    """
    x = 0
    y = 0
    path = [(x,y)] # instantiation
    
    while not (x== len(matrix)-1 and y == len(matrix[0])-1): # ends the end is reached
        if x == len(matrix)-1:
            y += 1
        elif y == len(matrix[0])-1:    
            x += 1
        else:
            if matrix[x+1, y] < matrix[x, y+1]:
                x+=1    
            elif matrix[x, y+1] < matrix[x+1, y]:
                y+=1      
            else:
                print("Wow, two adjacent choices are exactly the same. That's unexpected")
                break
        path.append( (x,y) ) 
        
#     # add final point
#     if x == len(matrix) - 1:
#         x+=1
#     if y == len(matrix[0]) - 1:
#         y+=1
    
    path.append( (x,y) )
        
    return path
    
    

In [16]:
pathLeastResistanceDownComplete(testArray)

[(0, 0),
 (1, 0),
 (1, 1),
 (1, 2),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 4),
 (4, 4),
 (4, 4)]

In [17]:
def pathLeastResistanceUp(matrix):
    """
    returns a list of coordinate tuples 
    at every coordinate pair, the one with the smallest value (between the left-adjacent and upper-adjacent choices) is chosen next
    the path ends when one of the sides of the matrix is reached
    starts at the bottom
    """

    x = len(matrix)-1
    y = len(matrix[0])-1
    path = [(x,y)] # instantiation
    
    while x > 0 and y > 0: # ends when a wall is reached
        if matrix[x-1, y] < matrix[x, y-1]:
            x-=1    
        elif matrix[x, y-1] < matrix[x-1, y]:
            y-=1      
        else:
            print("Wow, two adjacent choices are exactly the same. That's unexpected")
            break
        
        path.append( (x,y) ) 
        
    return path
    
    

In [18]:
# testing
pathLeastResistanceUp(testArray)

[(4, 4), (4, 3), (3, 3), (2, 3), (2, 2), (1, 2), (1, 1), (1, 0)]

In [19]:
def pathLeastResistanceUpComplete(matrix):
    """
    returns a list of coordinate tuples 
    at every coordinate pair, the one with the smallest value (between the left-adjacent and upper-adjacent choices) is chosen next
    the path ends when one of the sides of the matrix is reached
    starts at the bottom
    """

    x = len(matrix)-1
    y = len(matrix[0])-1
    path = [(x,y)] # instantiation
    
    while not (x == 0 and y == 0): # ends when a wall is reached
        if x==0:
            y-=1
        elif y==0:
            x-=1
        else:       
            if matrix[x-1, y] < matrix[x, y-1]:
                x-=1    
            elif matrix[x, y-1] < matrix[x-1, y]:
                y-=1      
            else:
                print("Wow, two adjacent choices are exactly the same. That's unexpected")
                break
        
        path.append( (x,y) ) 
        
    return path

In [20]:
# testing
pathLeastResistanceUpComplete(testArray)

[(4, 4), (4, 3), (3, 3), (2, 3), (2, 2), (1, 2), (1, 1), (1, 0), (0, 0)]

In [21]:
def findCommonTuples(downTuples, upTuples):
    """
    takes in a leastResistanceDown and leastResistanceUp return tuple
    returns list of shared tuples
    """
    # lazy method that accounts for all lists, assumes no special order
    commonTuples = set() # gets rid of duplicates
    
    for up in upTuples:
        for down in downTuples:
            if up==down:
                commonTuples.add(up) 
    
    return commonTuples

In [22]:
findCommonTuples(pathLeastResistanceDownComplete(testArray), pathLeastResistanceUpComplete(testArray))

{(0, 0), (1, 0), (1, 1), (1, 2), (2, 2), (2, 3), (4, 4)}

In [23]:
def findCommonTuplesOrdered(downTuples, upTuples):
    """
    takes in a leastResistanceDown and leastResistanceUp return tuple
    returns list of shared tuples, in the order that they encounter each other
    """

In [33]:
def pathSum(tuples, matrix):
    sum = 0
    for tup in tuples:
        x,y = tup
        sum += matrix[x,y]
        
    return sum

### Results

In [25]:
# get matrix from file

file = open('081_matrix.txt')

anArray = np.zeros((80, 80))

for i in range(80):
    aLine = file.readline()
    aLine = aLine.split(',') # the file has no spaces, thankfully
    tempRow = [int(x) for x in aLine] # convert string ints into ints
    anArray[i, :] = tempRow # set row of array
    
file.close()

print(anArray)

[[4445. 2697. 5115. ... 2758. 3748. 5870.]
 [1096.   20. 1318. ... 4187. 9353. 9377.]
 [9607. 7385.  521. ... 9515. 6385. 9230.]
 ...
 [2265. 8192. 1763. ... 7456. 5128. 5294.]
 [2132. 8992. 8160. ... 5634. 1113. 5789.]
 [5304. 5499.  564. ... 2751. 3406. 7981.]]


In [26]:
pathLeastResistanceUp(anArray)

[(79, 79),
 (79, 78),
 (78, 78),
 (77, 78),
 (76, 78),
 (76, 77),
 (76, 76),
 (76, 75),
 (76, 74),
 (76, 73),
 (76, 72),
 (75, 72),
 (75, 71),
 (74, 71),
 (74, 70),
 (73, 70),
 (73, 69),
 (73, 68),
 (73, 67),
 (73, 66),
 (73, 65),
 (72, 65),
 (72, 64),
 (71, 64),
 (70, 64),
 (70, 63),
 (69, 63),
 (68, 63),
 (68, 62),
 (68, 61),
 (68, 60),
 (68, 59),
 (68, 58),
 (68, 57),
 (68, 56),
 (67, 56),
 (67, 55),
 (67, 54),
 (66, 54),
 (66, 53),
 (65, 53),
 (65, 52),
 (64, 52),
 (64, 51),
 (64, 50),
 (63, 50),
 (63, 49),
 (62, 49),
 (61, 49),
 (60, 49),
 (59, 49),
 (58, 49),
 (57, 49),
 (56, 49),
 (56, 48),
 (56, 47),
 (55, 47),
 (55, 46),
 (54, 46),
 (54, 45),
 (53, 45),
 (53, 44),
 (53, 43),
 (52, 43),
 (51, 43),
 (51, 42),
 (51, 41),
 (51, 40),
 (51, 39),
 (50, 39),
 (50, 38),
 (50, 37),
 (50, 36),
 (49, 36),
 (49, 35),
 (49, 34),
 (48, 34),
 (47, 34),
 (46, 34),
 (45, 34),
 (44, 34),
 (43, 34),
 (43, 33),
 (43, 32),
 (42, 32),
 (41, 32),
 (41, 31),
 (41, 30),
 (40, 30),
 (40, 29),
 (40, 28),

In [27]:
pathLeastResistanceDown(anArray)

[(0, 0),
 (1, 0),
 (1, 1),
 (1, 2),
 (2, 2),
 (2, 3),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 6),
 (4, 7),
 (5, 7),
 (5, 8),
 (6, 8),
 (7, 8),
 (8, 8),
 (9, 8),
 (9, 9),
 (10, 9),
 (11, 9),
 (11, 10),
 (11, 11),
 (12, 11),
 (12, 12),
 (12, 13),
 (13, 13),
 (13, 14),
 (13, 15),
 (13, 16),
 (14, 16),
 (15, 16),
 (16, 16),
 (16, 17),
 (16, 18),
 (17, 18),
 (17, 19),
 (17, 20),
 (18, 20),
 (18, 21),
 (18, 22),
 (19, 22),
 (19, 23),
 (20, 23),
 (20, 24),
 (21, 24),
 (22, 24),
 (22, 25),
 (23, 25),
 (23, 26),
 (24, 26),
 (24, 27),
 (24, 28),
 (24, 29),
 (24, 30),
 (24, 31),
 (25, 31),
 (26, 31),
 (27, 31),
 (28, 31),
 (28, 32),
 (29, 32),
 (30, 32),
 (30, 33),
 (31, 33),
 (32, 33),
 (33, 33),
 (34, 33),
 (34, 34),
 (34, 35),
 (34, 36),
 (34, 37),
 (35, 37),
 (36, 37),
 (37, 37),
 (37, 38),
 (38, 38),
 (39, 38),
 (40, 38),
 (40, 39),
 (40, 40),
 (40, 41),
 (40, 42),
 (41, 42),
 (42, 42),
 (42, 43),
 (42, 44),
 (42, 45),
 (43, 45),
 (44, 45),
 (44, 46),
 (44, 47),
 (44, 48),
 (44, 49),
 (45, 

In [28]:
findCommonTuples(downTuples, upTuples)

NameError: name 'downTuples' is not defined

In [34]:
downTuplesComplete = pathLeastResistanceDownComplete(anArray)
pathSum(downTuplesComplete, anArray)
# wrong answer...

556858.0

In [35]:
upTuplesComplete = pathLeastResistanceUpComplete(anArray)
pathSum(upTuplesComplete, anArray)
# wrong answer...

563261.0

### IMplementation part 2
Nabbed from https://www.mathblog.dk/project-euler-81-find-the-minimal-path-sum-from-the-top-left-to-the-bottom-right-by-moving-right-and-down/ 

(I got impatient)


In [36]:
# planning: from bottom corner, work way up by choosing the lesser
# of the number to the right and the number to the bottom
# then, sum the lesser number to the cell

# will work in a diagonal pattern from the bottom up and to the right

In [1]:
def genMatrixCoords(matrix):
    """generates list of coordinates to traverse, in 
    order
    only works for square matrix"""
    
    coords = []
    length = len(matrix)
    
    # widerning
    for i in range(length):
        for j in range(0,i+1):
            coords.append( (length-1 - j  , length-1 -i+j ))
      
    # narrowing
    for i in range(length-2,-1,-1):
        for j in range(0, i+1):
            coords.append( (i-j , j) )
        
    
    return coords

In [66]:
# test 
A = np.eye(3)
coords = genMatrixCoords(A)
print(coords)

[(2, 2), (2, 1), (1, 2), (2, 0), (1, 1), (0, 2), (1, 0), (0, 1), (0, 0)]


In [6]:
def solution(matrix):
    """
    assumes matrix is square
    """
    matCopy = matrix.copy() # prevents alteation of original matrix
    coords = genMatrixCoords(matrix)
    length = len(matrix)
    
    for coord in coords[1:]: # ignoring first coordinate, which is the bottom right corner
        x, y = coord
        
        #if hugging bottom wall
        if x == length-1:
            matCopy[x,y] += matCopy[x,y+1] # automatically choose cell to the right
        
        #if hugging right wall
        elif y == length-1:
            matCopy[x,y] += matCopy[x+1,y] # automatically choose cell below it
    
        else: 
            matCopy[x,y] += min(matCopy[x+1,y], matCopy[x,y+1]) # made the error of adding to matrix insteaad of matrix[x,y]
            
#         print(matrix)
         
    print(matCopy)
    
    return matCopy[0,0]

In [83]:
print(genMatrixCoords(testArray))

[(4, 4), (4, 3), (3, 4), (4, 2), (3, 3), (2, 4), (4, 1), (3, 2), (2, 3), (1, 4), (4, 0), (3, 1), (2, 2), (1, 3), (0, 4), (3, 0), (2, 1), (1, 2), (0, 3), (2, 0), (1, 1), (0, 2), (1, 0), (0, 1), (0, 0)]


In [84]:
testArray = np.array([[131, 673, 234, 103, 18], [201, 96, 342, 965, 150],[630, 803, 746, 422, 111], [537, 699, 497, 121, 956], [805, 732, 524, 37, 331]])


In [85]:
# test on smaller case
minSum = solution(testArray)
print(minSum)

[[131 673 234 103  18]
 [201  96 342 965 150]
 [630 803 746 422 111]
 [537 699 497 121 956]
 [805 732 524 368 331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422  111]
 [ 537  699  497  121 1287]
 [ 805  732  524  368  331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422  111]
 [ 537  699  497  121 1287]
 [ 805  732  892  368  331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422  111]
 [ 537  699  497  489 1287]
 [ 805  732  892  368  331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422 1398]
 [ 537  699  497  489 1287]
 [ 805  732  892  368  331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422 1398]
 [ 537  699  497  489 1287]
 [ 805 1624  892  368  331]]
[[ 131  673  234  103   18]
 [ 201   96  342  965  150]
 [ 630  803  746  422 1398]
 [ 537  699  986  489 1287]
 [ 805 1624  892  368  331]]
[[ 131  673  234  103   18]
 [ 201   9

In [7]:
# test on special case
trickyArray = np.array([[1,3,3,3,3],
                       [1,2,3,3,3],
                       [1,3,4,3,3],
                       [1,3,3,2,3],
                       [1,1,1,1,2]])
print(solution(trickyArray)) # the answer is 10

[[10 16 17 14 14]
 [ 9 13 14 11 11]
 [ 8 11 11  8  8]
 [ 7  8  7  5  5]
 [ 6  5  4  3  2]]
10


### Results pt 2


In [93]:
# get matrix from file

file = open('081_matrix.txt')

anArray = np.zeros((80, 80))

for i in range(80):
    aLine = file.readline()
    aLine = aLine.split(',') # the file has no spaces, thankfully
    tempRow = [int(x) for x in aLine] # convert string ints into ints
    anArray[i, :] = tempRow # set row of array
    
file.close()

print(anArray)

[[4445. 2697. 5115. ... 2758. 3748. 5870.]
 [1096.   20. 1318. ... 4187. 9353. 9377.]
 [9607. 7385.  521. ... 9515. 6385. 9230.]
 ...
 [2265. 8192. 1763. ... 7456. 5128. 5294.]
 [2132. 8992. 8160. ... 5634. 1113. 5789.]
 [5304. 5499.  564. ... 2751. 3406. 7981.]]


In [98]:
minSum = solution(anArray)
print(f"Solution is: {minSum}")

Solution is: 427337.0


## Reflections

This took me over a month since I started it to finish. I only finished after googling
a solution. (Finished this 3/11/19, and probably started sometime last year.)

I learned the notion of "dynamic programming," and was introduced to a concept that I
hadn't seen before. 

I don't think I would have gotten the answer even if I kept trudging through.
 
Credit to: https://www.mathblog.dk/project-euler-81-find-the-minimal-path-sum-from-the-top-left-to-the-bottom-right-by-moving-right-and-down/